import type { NextPage, GetStaticPropsContext } from 'next'
import Head from 'next/head';
import Image from 'next/image'
import Link from 'next/link'
import React from 'react';
import { getPostPage, getPostPages } from '../../lib/api';
import { IPost } from '../../types/generated/contentful';
import styles from '../../styles/Home.module.css'

interface Props {
  page: IPost,
}

const Post: NextPage<Props> = ({ page }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CookBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {page.fields.name}
        </h1>

        <p className={styles.description}>
          AGE:
          <code className={styles.code}>{page.fields.age}</code>
        </p>

        <Link href="/">
          <a className={styles.button}>&larr; Back to home page</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Post

export async function getStaticProps(context: GetStaticPropsContext) {
  const id = String(context.params?.id);
  const page = await getPostPage(id);
  return {
    props: { page }, // will be passed to the page component as props
  }
}

export async function getStaticPaths() {
  const pages = await getPostPages();
  const paths = pages.map(page => ({ params: { id: page.fields.name } }));

  return {
    paths: paths,
    fallback: false,
  };
}
